### ISSUE TITLE
Console error on world load

### ISSUE THREAD

**Issue by ottyn** [farling42/fvtt-easy-regions#3]
Foundry 12.327
PF2e 6.0.4
Easy Regions 0.3.1

Receive the following console error on world load.

![image](https://github.com/farling42/fvtt-easy-regions/assets/97130150/bc34077f-56f6-4127-b155-f495642f21e5)

**Comment by farling42** [comment]
I haven't been able to reproduce this.
Are you getting this error repeatedly, or did it only occur once?

**Comment by farling42** [comment]
Version 0.4.0 should fix this problem.

**Comment by ottyn** [comment]
Issue appears to be resolved after update.  Thank you.
