### ISSUE TITLE
[Feature Request] Don't show difficult terrain cost when behavior is disabled

### ISSUE THREAD

**Issue by joeparis** [farling42/fvtt-easy-regions#8]
Currently when you have a region with a difficult terrain behavior the extra cost for movement is shown whether or not that behavior is enabled or disabled. I would like to ask that the extra cost not be shown when the behavior is disabled, please.

**Comment by farling42** [comment]
The cost calculation is performed by the core PF2 system, not my module.
So I assume that the core PF2 system is always taking regions into account even when they are disabled.

**Comment by joeparis** [comment]
Ah, I see. Thanks for looking at this.

**Comment by farling42** [comment]
My PR for the PF2e game system can be tracked at https://github.com/foundryvtt/pf2e/pull/16973

**Comment by farling42** [comment]
Patched 7 hours ago by Reyzer, https://github.com/foundryvtt/pf2e/commit/b287239f1ae7435c659832c5d776559ed01eb43b

**Comment by farling42** [comment]
Pathfinder system version 6.5.0 contains a fix for this (but other environment regions which are disabled still affect tokens).

**Comment by joeparis** [comment]
Wow, thanks for following up!
